//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL_DEV_TORRENTS
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int FileId { get; set; }
        public string Name { get; set; }
        public string Size { get; set; }
        public int Torrent_Id { get; set; }
    
        public virtual Torrent Torrent { get; set; }
    }
}
