//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL_DEV_TORRENTS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Torrent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Torrent()
        {
            this.Files = new HashSet<File>();
        }
    
        public int Torrent_Id { get; set; }
        public System.DateTimeOffset RegistredAt { get; set; }
        public string Size { get; set; }
        public string Title { get; set; }
        public string Torrent_Hash { get; set; }
        public Nullable<int> Torrent_TrackerId { get; set; }
        public Nullable<int> Forum_Id { get; set; }
        public string Content { get; set; }
        public string Dir_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<File> Files { get; set; }
        public virtual Forum Forum { get; set; }
    }
}
